WeaselGames/godot_luaAPI

- lua.cpp
this fixes the issue i mentioned in discord where function names longer than 15 characters were getting converted incorrectly and inserting garbage into the lua globals table. i believe this was due to getting `c_str()` from a temporary string that was going out of scope.
i have tested this fix and it appears to work perfectly with long function names.
> fix godot string -> std::string conversion bug

- README.md
- lua.cpp
- lua.h
this allows a GDScript program to call global functions on a user's lua script. this is useful for a variety of reasons, for me it's the ability to create a "hooks" system like this:
```lua
function on_player_spawned(name, id)
print("player has been spawned with name: "..name.." and id: "..id)
end
add_hook("player_spawned", "on_player_spawned")
```
and then in gdscript:
```gdscript
func add_hook(hook_name: String, function_name: String) -> void:
hooks[hook_name].append(function_name)
func spawn_player(name: String, id: int) -> void:
for hook in hooks["player_spawned"]:
lua.callFunction(self, hook, [name, id])
```
> add callFunction method to lua class

- README.md
- lua.cpp
- lua.h
This PR makes GD Variants with types VECTOR2, VECTOR3 or COLOR to be pushed as full userdatas. Since these types aren't referenced, I don't think this can lead to any problem (they are `memcpy`'ed)
```
void* userdata = (Variant*)lua_newuserdata( state , sizeof(Variant) );
memcpy( userdata , (void*)&var , sizeof(Variant) );
```
- These userdatas have a basic metatable, with the following metamethods defined:
```
__add
__sub
__mul
__div
__index
__newindex
```
So basic operations over Vector2/Vector3/Color can be more simple:
```
local v1 = Vector2( 0.5 , 100 )
local v2 = Vector2( 100 , 0.5 )
print( v1 * v2 ) -- prints "(50,50)"
```
- It also exposes a constructor for these types
```
local v2 = Vector2( 100 , 100 )
local v3 = Vector3( 100 , 100 , 200 )
local c = Color( 1 , 0 , 0 , 0.5 )
``` …
> Vector2,Vector3 and Color types passed as userdata

- README.md
- config.py
- docs/Lua.xml
- lua.cpp
- lua.h
- This PR solves a problem with `Lua::getVariant(int index)`. When passing a relative index (index<0), the proper way to iterate with `lua_next()` is indeed using `index-1`, but when index>0, this should remain only `index`. This was crashing my project.
- Also, it gives a proper way to call lua functions from GDScript. Now we could check beforehand if the function actually exists, and we can optionally set it as a protected call. The arguments order were moved. Before, the first parameter `Object*` doesn't had any utility. I propose to use this same pattern of the same last 3 optional parameters ( bool protected_call , Object* callback_caller , String callback ) in doFile and doString as well, what do you think? To call functions outside protected mode could maybe be more performant, …
> Optional protected call for callFunction & fixing iterate over table

- README.md
- docs/Lua.xml
- lua.cpp
- lua.h
- luaCallable.cpp
- luaCallable.h
Callables are now passed as userdata with a metatable defining the __call method. This allows you to push a callable to lua as a function.
Additionally lua functions can now be pulled as a Callabled, to achieve this a new class was created `luaCallable`. It is a `customCallable`. It works by storing a luaL_ref of the lua function. When the Callable is called it will execute the function on the lua stack.
Since Callables can now be passed with push_variant this removes the need for expose_function thus it has been removed.
> Callables as userdata

- README.md
- config.py
- docs/Lua.xml
- docs/LuaError.xml
- docs/LuaThread.xml
- lua.cpp
- lua.h
- luaCallable.cpp
- luaCallable.h
- luaError.cpp
- luaError.h
- luaThread.cpp
- luaThread.h
- luasrc/lauxlib.c
- register_types.cpp
This PR changes quite a bit and adds a lot of new features.
A new type was created that inherits RefCounted called LuaError. This type stores 2 properties:
- msg: Contains the error message.
- type: Contains the error type.
The error type is a enumeration with the following possible values:
- ERR_NONE: Indicates no error.
- ERR_TYPE: Indicates a error with argument types.
- ERR_RUNTIME: Indicates a generic runtime error.
- ERR_SYNTAX: Indicates a syntax error.
- ERR_MEMORY: Indicates a memory error.
- ERR_ERR: Indicates a error with the internal error handler. Should be reported.
- ERR_FILE: Indicates a error while opening a file.
This type is now returned by any function that can run into a error. Additionally, gd functions expose to lua can return this type to raise a error in the lua …
> Error Handling, Coroutines and Object metamethod overrides.

- lua.cpp
The callable class no longer has a member 'call' since it has been renamed to 'callp'.
> Fix Callable's method rename

- README.md
- src/luaState.cpp
Fixed a bug caused by the recent changes to LuaError where we were checking err == nullptr instead of err != nullptr.
Fixed several typos in the readme as well as the nightly links.
> Typo and bug fixes

- README.md
- docs/LuaAPI.xml
- docs/LuaThread.xml
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaCallable.cpp
- src/classes/luaThread.cpp
- src/classes/luaThread.h
- src/luaState.cpp
- src/luaState.h
- src/metatables.cpp
Changes:
- Changed the argument order for push_variant moving the name to be the first argument.
- Changed the argument order for expose_constructor moving the name to be the first argument.
- Added new metatable for mt_RefCounted.
- Added support to LuaState::pushVariant() for mt_RefCounted.
- Added support to LuaState::getVariant() for mt_RefCounted.
- Changed memory management. We now ignore Lua's garbage collector. Instead, all memory owned by the lua state is free'd at its death. This was a bi product of the change, and we may want to add support back in the future for Luas garbage collector.
- Readme and DOC info updated as well as some grammatical fixes.
> Added support for RefCounted types via lightuserdata

- README.md
- doc_classes/LuaCallableExtra.xml
- doc_classes/LuaThread.xml
- doc_classes/LuaTuple.xml
- register_types.cpp
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaCallableExtra.cpp
- src/classes/luaCallableExtra.h
- src/classes/luaTuple.cpp
- src/classes/luaTuple.h
- src/luaState.cpp
- src/luaState.h
- src/metatables.cpp
- testing/run_tests.gd
- testing/tests/LuaAPI.expose_function.gd
- testing/tests/general.object_metamethods.gd
Changes:
- Fixed bug with arguments passed to mt_Callable
- Added new LuaTuple type. The type is a container for array. resolves #64 
- Added new LuaCallableExtra type. A wrapper class for Callable to support extra functionality. Such as passing ref or taking a tuple argument. resolves #63
- Removed the lua_funcs method check from objects. lua_fields now serves both roles. 
- Added some more tests
> LuaTuple and LuaCallableExtra

- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/metatables.cpp
This PR fixes #75, the issue was caused when lua invoked mt_Object's __gc meta method for garbage collection. Sometimes it would be called during an none optimal time. Instead this PR makes all object live the life of the LuaAPI object.
> Bug fix with lua garbage collector

- doc_classes/LuaCallableExtra.xml
- src/classes/luaCallableExtra.cpp
- src/classes/luaCallableExtra.h
- testing/tests/LuaAPI.expose_function.gd
Previously the argc property of LuaCallableExtra expected the LuaTuple to be counted but not the LuaAPI reference. Instead now neither are counted and arc is to be used for additional arguments only. Hopefully this helps remove some confusion. 
Changes:
- LuaCallableExtra no longer expects LuaTuple to be counted.
- LuaCallableExtra now checks if the Callable instance is invalid before attempting to invoke it.
- LuaCallableExtra now has tuple, wants_ref, and argc as properties.
- LuaCallableExtra  has a new static method to go with with_tuple and with_ref, with_ref_and_tuple.
- Tests modified according to changes.
> Remove confusing argc behavior

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/unit_testing.yml
- .github/workflows/windows.yml
- .gitmodules
- SCsub
- config.py
- external/SCsub
- src/lua/lua.hpp
- src/luaState.cpp
This bumps LuaJIT to v2.1 in order to support apple silicone. If it proves to be too unstable we will revert back. But I would prefer wider coverage. 
This also adds support for cross compiling for 32 bit linux from 64 bit linux. Supoort needs to be looked into still for cross compiling x86 linux to arm. And 64 bit windows to 32 bit windows. And maybe android and ios builds too in the future.
> Add support for cross arch builds of luaJIT + lua 5.1

- .github/workflows/gdextension.yml
The asset library in the editor expects there to be some containing folder. See https://github.com/godotengine/godot/issues/75712
> Fix for asset library

- README.md
- config.py
- doc_classes/LuaAPI.xml
- doc_classes/LuaCoroutine.xml
- project/demo/HelloLua.gd
- project/testing/tests/LuaCoroutine.resume.gd
- project/testing/tests/LuaCoroutine.yield_await.gd
- register_types.cpp
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaCoroutine.cpp
- src/classes/luaCoroutine.h
- src/luaState.cpp
Mostly resolves #95, I chose not to have the parent lua state keep track of threads. Seemed unneeded.
This PR renames LuaThread to LuaCoroutine in favor of being less confusing.
- Support to pull coroutines created via coroutine.create as a LuaCoroutine. I could not get pushing LuaCourtines working however. For some reason it just would not work. Hopefully a fix can be found in the future.
- new method on the LuaAPI class new_coroutine, which takes no arguments and returns a LuaCoroutine
- the new_thread static method has been removed from the LuaThread/LuaCoroutine class in favor of the new method on LuaAPI.
Online documentation needs to be updated to reflect changes.
> Rename LuaThread to LuaCoroutine

- src/classes/luaAPI.cpp
- src/classes/luaCallable.cpp
Resolves #101 
Currently we do not capture errors returned from loading code as a string in LuaAPI::doString. We also do not set an error handler for the pcall in luaCallable. This will help increase the error message consistency and quality.
> Improve error handling

- doc_classes/LuaCoroutine.xml
- src/classes/luaCoroutine.cpp
- src/classes/luaCoroutine.h
- src/metatables.cpp
Previously LuaCoroutine.load_string would not handle an error if one occurred. This PR fixes that.
> Handle LuaCouroutine load_string errors

- doc_classes/LuaCoroutine.xml
- src/classes/luaCoroutine.cpp
- src/classes/luaCoroutine.h
Already documented:
`interrupt_execution()` will throw an error `execution interrupted`
`kill()` will throw an error `execution terminated` and will not stop until the thread exits all the way to the top stack.
> Create interrupt_execution and kill methods on LuaCoroutine

- doc_classes/LuaAPI.xml
- doc_classes/LuaCoroutine.xml
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaCoroutine.cpp
- src/classes/luaCoroutine.h
- src/luaState.cpp
- src/luaState.h
PRs #110 and #112 introduce some issues.
Before there was no way to force a lua coroutine or state to stop executing. Meaning scripts could easily crash the application or etc.
- #110 Added the method `pause_execution` to LuaCoroutine. Which would call `lua_yield` in a hook it sets at the time the function is called. The hook would only run once.
- #112 Added the methods `interrupt_execution` and `kill`. Both of which would create a hook in the same manner as before. `interrupt_execution`  would raise an error one time. Kill would do the same, but never remove its hook.
The intent was that the lua state would be executing on a separate thread when these methods were called. However accessing or modifying the lua state on multiple threads is not safe.
Instead of having predefined hooks and …
> Add methods get_running_coroutine,set_hook and yield_state

- src/classes/luaCallableExtra.cpp
- src/classes/luaCallableExtra.h
- src/luaState.cpp
- src/luaState.h
Our previous method of passing arguments to callp was a little crude. In discord a bug was brought up which was intermittent and unpredictable. It was noticed when calling methods on objects. Results would very on weather args would be properly sent under certain conditions. I still do not fully understand where or why the bug happened. But I simplified the method of allocating space for arguments and it seems to be resolved now.
CC @Griiimon
> Simplified callp interactions with arguments

- .github/workflows/macos.yml
Resolves #97 
Currently macOS keeps x86_64 and arm64 bins along with the universal ones. This resolves that.
> Delete none universal bins

- .github/workflows/gdextension-unit-tests.yml
- README.md
- scripts/codespell.sh
- src/luaState.cpp
A couple random bug fixes and a README update
- Bug with lua hook pushing a nil value onto the state if the Callable returned nothing.
- Bug with module version of the hooks overriding argument values.
- Codespell script had a random command.
> Fix lua_hook pushing a nil value if hook returns nothing

- .github/workflows/gdextension-unit-tests.yml
- .github/workflows/gdextension.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/module-unit-tests.yml
- README.md
- external/SConscript
Currently linux builds are built on Ubuntu 20.04, this means its a fairly new glibc version and wont work on many still supported LTS releases of linux. Buildroot forces use of an older glibc version.
> Start useing buildroot for linux builds

- doc_classes/LuaCoroutine.xml
- project/testing/tests/LuaCoroutine.resume.gd
- project/testing/tests/LuaCoroutine.yield_await.gd
- src/classes/luaCoroutine.cpp
- src/classes/luaCoroutine.h
- src/luaState.cpp
- src/luaState.h
Previously we stored a reference to the GDScript function state in order to resume later, this PR utilizes the signal await binds to instead and cleans up after.
LuaCoroutine.resume now also takes an array of arguments that can be passed to yield() in lua
> Improvments to yield_await

- doc_classes/LuaAPI.xml
- project/demo/HelloLua.gd
- project/testing/tests/LuaAPI.call_function.gd
- project/testing/tests/LuaAPI.expose_constructor.gd
- project/testing/tests/LuaAPI.expose_function.gd
- project/testing/tests/LuaCoroutine.resume.gd
- project/testing/tests/LuaCoroutine.yield_await.gd
- project/testing/tests/general.base_types.gd
- project/testing/tests/general.object_metamethods.gd
- project/testing/tests/general.object_push.gd
- project/testing/tests/luaAPI.do_file.gd
- project/testing/tests/luaAPI.do_string.gd
- project/testing/tests/luaAPI.pull_variant.gd
- project/testing/tests/luaAPI.push_variant.gd
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/luaState.h
- src/metatables.cpp
Currently if a object does not define an `__index` or a `lua_fields` method all fields/methods will be allowed. And if it does its treated as a whitelist.
This PR makes it so if its not defined by default no fields/methods will be allowed. And adds a permissive mode which when enabled will allow all fields/methods by default and treat lua_fields as a blacklist instead.
`__newindex` and `__index` still take priority over all though.
> Add permissive mode

- doc_classes/LuaAPI.xml
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/luaState.cpp
- src/metatables.cpp
This PR fixes some pretty bad memory leaks. Somewhere along the line a bad assumption was made that memcpy had to be used instead of just storing the value. While just storing the value does work for module builds, because of how GDExtension works it cant really handle a null Variant. This is because all variants even null ones point to a Variant in the engine its self. Thus when we assign a real value to a null variant it causes a memory exception. For this reason memmove was used instead. As a safe way to transfer the value to lua. The ref count is also incremented for RefCounted's when passed to lua. And de incremented in the lua gc.
The configure_gc method has also been added. It is a direct exposure of [lua_gc](https://www.lua.org/manual/5.4/manual.html#lua_gc) from the C API.
> Use memmove instead of memcpy

- .github/workflows/runner.yml
- project/demo/HelloLua.gd
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/luaState.cpp
- src/metatables.cpp
The previous set of changes caused some regression due to the differences of how GDExtension and Modules work. memove is needed for GDExtension because all Variants for it are pointers to Variants living in the engine, assigning to a null Variant allocated by lua will cause a null pointer deref. Therefore we skip the assignment operator by using memmove. We need to do some manually ref counting to make this work.
For modules memmove caused a lot more issues so this PR has the Module version use the assignment operator. 
The other major change was we now test if a Callable is custom and send it as a blank LuaCallableExtra instead. We do this to create a wrapper to the callable custom which will always have a RefCounted. Without this we have no way to manually increment the ref counter so …
> Fix some regression issues

- src/luaState.cpp
tiny edit to avoid squared key lookup times when pushing variant dictionaries
> pushVariant: Save key array for loop

- src/luaState.cpp
- src/metatables.cpp
This fixed some crashes that were reported in discord. There was 2 separate issues. One which effected module builds and one which effected GDExtension builds.
~The issue was with the fact that we create Variant pointers with `lua_newuserdata`. The can cause issues because of the way Variants work, for primitives it will store the literal value. Object and RefCounted types are pointers. The issue we were having is Variant has an assignment operator that calls clear() for primitives this sets the 0 value, for objects and refcounted types it calls their clear() method. Its a switch case for the type. Objects go to default. However since our initial Variant was allocated by lua its dirty memory so it has an invalid type that it tries to use to lookup its clear method. But since its invalid …
> Fixed crashes with pushVariant

- .github/workflows/gdextension-unit-tests.yml
- .github/workflows/runner.yml
- README.md
- project/addons/luaAPI/luaAPI.gdextension
- project/project.godot
- register_types.cpp
- scripts/SConstruct
- src/classes/luaCallableExtra.cpp
Not many changes were needed to make this happen, a couple changes to the GDExtension entry point is all really.
> Bump godot version to 4.1

- src/luaState.cpp
- src/metatables.cpp
I recently discovered `memnew_placement` exists. Which specifically allows us to handle allocation and place the Variant. This PR removes some hacky work arounds I had done before.
> Use memnew_placement instead of memmove

- project/testing/tests/LuaAPI.expose_function.gd
- register_types.cpp
- src/classes/luaAPI.cpp
- src/classes/luaCallableExtra.cpp
- src/luaState.cpp
- src/luaState.h
- src/metatables.cpp
This should result in some small performance improvements as we avoid pulling the api ref from the state unless needed now. This PR also adds support to move a lua funcref from one state to another.
> getVariant no longer requires api ref

- doc_classes/LuaAPI.xml
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
This PR adds the ability to control the max amount of memory the Lua state can use.
- **memory_limit property** this sets the max allowed memory usage in bytes, if 0 there is no limit. Defaults to 0
- **get_memory_usage method** this returns the current memory usage of the Lua state in bytes.
> Add max memory usage restrictions

- doc_classes/LuaAPI.xml
- project/testing/tests/LuaAPI.expose_constructor.gd
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/luaState.h
- src/metatables.cpp
Now that our memory management is streamlined there is no need to treat objects made by lua any different making expose_constructor obsolete. Instead you can either return or push obj.new as a global. This also allows for constructor args.
> Remove expose_constructor

- config.py
- doc_classes/LuaAPI.xml
- doc_classes/LuaCallableExtra.xml
- doc_classes/LuaCoroutine.xml
- doc_classes/LuaDefaultObjectMetatable.xml
- doc_classes/LuaError.xml
- doc_classes/LuaObjectMetatable.xml
- doc_classes/LuaTuple.xml
- project/testing/tests/LuaAPI.call_function.gd
- project/testing/tests/LuaAPI.expose_constructor.gd
- project/testing/tests/LuaAPI.expose_function.gd
- project/testing/tests/LuaCoroutine.resume.gd
- project/testing/tests/LuaCoroutine.yield_await.gd
- project/testing/tests/general.base_types.gd
- project/testing/tests/general.object_metamethods.gd
- project/testing/tests/general.object_push.gd
- project/testing/tests/luaAPI.do_file.gd
- project/testing/tests/luaAPI.do_string.gd
- project/testing/tests/luaAPI.pull_variant.gd
- project/testing/tests/luaAPI.push_variant.gd
- register_types.cpp
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaObjectMetatable.cpp
- src/classes/luaObjectMetatable.h
- src/metatables.cpp
This PR adds some new types for better metatable control over objects. 
- **New `LuaObjectMetatable` type**: this is a interface class meant to be used to define metatables. 
- **New `object_metatable` property on `LuaAPI`**: This is the default metatable to use for object which do not have a lua_metatable property them selfs.
- **New `LuaDefaultObjectMetatable` type**: this is the type that  `object_metatable` defaults to, it provides the same functionality with metatables and metamethods we had before this update. The `LuaAPI` permissive property has been moved to this class now. It will yield metamethod calls to the object if it defines them like before. Otherwise looks for the `lua_fields` method which is either a blacklist or a whitelist depending on `permissive`.
- the `permissive` …
> Add LuaObjectMetatable type

- doc_classes/LuaAPI.xml
- doc_classes/LuaCoroutine.xml
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaCoroutine.cpp
- src/classes/luaCoroutine.h
- src/luaState.cpp
- src/luaState.h
> Registry indexing, function calls, global manipulation, now all recursive!

- .github/workflows/linux.yml
- .github/workflows/macos-build.yml
- .github/workflows/macos-package.yml
- .github/workflows/runner.yml
- .github/workflows/windows.yml
The need has been expressed by multiple people for c# support. Well while technically there is no reason c# should not work with this module. There is known to be several issues with it overall. Hopefully these are issues that can be fixed with time. But this will at least allow people to see what works and what does not. 
This PR also fixes the formatting of the macOS editor release builds
> Mono actions for release builds

- src/classes/luaAPI.cpp
- src/classes/luaCoroutine.cpp
- src/luaState.cpp
This PR adds support for UTF8 encoded strings. Part of the way this was implemented was we no longer assume ascii, rather we assume UTF8. I don't think any issues should come from this but we will see. In the future we might need to look into supporting both some how. This makes this PR 1/2 to fix #152, PR number 2 should come shortly for the v1.x release of this module.
This PR also adds the FFI library to luaJIT builds which resolves #159
> Add FFI & UTF8

- .github/workflows/linux.yml
- .github/workflows/macos-package.yml
- .github/workflows/runner.yml
- .github/workflows/windows.yml
- scripts/mono_instructions.txt
A quick fix for mono glue generation mistake discovered in #164, we generated it but never built it.
> Fix mono glue generation

- .github/workflows/linux.yml
- .github/workflows/macos-package.yml
64 bit debug templates were being sent to the wrong artifact.
Should resolve the issue brought up in https://github.com/WeaselGames/godot_luaAPI/pull/165#issuecomment-1748023960
> Fix mono export template builds

- README.md
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaCallable.cpp
- src/classes/luaCallable.h
- src/luaState.cpp
GDExtension should get access to these coming godot 4.2, but until then we can get the fix implemented for module builds.
Until GDExtension builds also have the fix, all lua Callables still take only a Godot array.
> Add back CallableCustom for module builds

- .github/workflows/runner.yml
- config.py
- doc_classes/LuaAPI.xml
- doc_classes/LuaFunctionRef.xml
- register_types.cpp
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/classes/luaFunctionRef.cpp
- src/classes/luaFunctionRef.h
- src/luaState.cpp
Since C# does not currently support CallableCustoms this PR adds a setting to the LuaAPI class, `luaAPI.use_callables`. It defaults to true. When set to true Lua functions pulled from the Lua state will use the LuaCallable type which is a CallableCustom. For c# or even gdScript to get around #155 it can be set to false to use the LuaFunctionRef type instead which is a RefCounted. It behaves identical to the LuaCallable type but uses an `invoke` method instead.
This is what the README example would look like for c# now
```cs
using Godot;
using System;
public partial class Node2D : Godot.Node2D
{
private LuaApi lua = new LuaApi();
public void LuaPrint(string message) {
GD.Print(message);
}
public override void _Ready() {
lua.UseCallables = false;
Godot.Collections.Array libraries = new()
{ …
```
> Add LuaFuntionRef type

- src/metatables.cpp
Fixes a bug reported in Discord.
> Deincermint ref count rather then calling the deconstructor

- SConstruct
- SCsub
- doc_classes/LuaAPI.xml
- external/SCsub
- lua_libraries/.gitignore
- lua_libraries/README.md
- lua_libraries/SConscript
- lua_libraries/SCsub
- lua_libraries/codegen.py
- lua_libraries/lua_libraries.h
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
- src/luaState.cpp
- src/luaState.h
This idea spun up due to https://github.com/WeaselGames/godot_luaAPI/issues/100#issuecomment-1760685532
This is a potential solution for both #100 and #144.
The steps to statically include a lua c library like lpeg, is to download its source code. Place the source in a folder under the lua_libraries folder with the exact library name, for lpeg this would be `lpeg`.  All lower case an no version. The next time the addon is built it will be auto detected by codegen and available to bind_libraries.
Before merging I would like to hear some feedback from @GokuHiki
This has been tested with lpeg on linux using both modules and gdextension so far. I wont be suprised if something breaks along the way.
> Simple codegen for lua c library static inclusion

- doc_classes/LuaObjectMetatable.xml
- src/classes/luaObjectMetatable.cpp
- src/classes/luaObjectMetatable.h
- src/luaState.h
- src/metatables.cpp
> Stop metatables from being overwritten/read from

- .github/workflows/macos-build.yml
- doc_classes/LuaAPI.xml
- src/classes/luaAPI.cpp
- src/classes/luaAPI.h
The lack of support for this was just an oversight. do_file and do_string will now take an optional second argument that should be an array of arguments. And now return a Variant instead of a LuaError.
Example
```gdscript
func _ready():
var lua: LuaAPI = LuaAPI.new()
lua.bind_libraries(["base", "table", "string"])
var ret = lua.do_string("""
local a, b = ...
print(a, b)
return a + b
""", [4, 6])
if ret is LuaError:
print("ERROR %d: %s" % [ret.type, ret.message])
return
print(ret)
```
> Support argument passing and return to do_file/string
